### ISSUE TITLE
Multiple SPFx generators on the same node version

### ISSUE THREAD

**Issue by lovengren** [JonasBjerke89/spfx-using-nvm#1]
Hi Jonas,

First of all great PowerShell module! 

However in case of different SPFx generators on the same node version your script could potentially overwrite the globally installed SPFx generator, making older projects on the same node version unstable when adding new web parts. 

Perhaps it won't pose any problems in practice, however I believe that the SPFx generators could be installed locally to handle potential conflicts.

Best regards,
Mikkel Løvengren

**Comment by JonasBjerke89** [comment]
Thanks for your input.

It is now fixed and available in the current release.
